### ISSUE TITLE
the aligner could use the same sentence multiple times in the output alignments

### ISSUE THREAD

**Issue by wangpd** [rsennrich/Bleualign#23]
I found one weird example:
Input target text file is:

> A
> B

while the output alignment of the target side is:

> A
> A B

**Comment by rsennrich** [comment]
Hello Pidong,

can you please provide a minimal reproducible example for this bug report?

thank you and best wishes,
Rico

**Comment by rsennrich** [comment]
closing this due to lack of reproducible example.
