### ISSUE TITLE
ImportError: No module named align

### ISSUE THREAD

**Issue by echan00** [rsennrich/Bleualign#28]
Getting the error below, not exactly sure where the  'align' module is supposed to be

```
Traceback (most recent call last):
  File "./bleualign.py", line 9, in <module>
    from bleualign.align import Aligner
  File "/Users/erikchan/Workspace/nda-ai/sentencealignment/bleualign/bleualign.py", line 9, in <module>
    from bleualign.align import Aligner
ImportError: No module named align
```

**Comment by echan00** [comment]
It was a silly mistake :)

**Comment by quinnanya** [comment]
@echan00 What did you do to fix it? I think I'm rerunning the same command that worked earlier, but now I'm getting this error too when running `./bleualign.py -s corpus/fr001_qu.txt -t corpus/001c-sentences.txt --srctotarget corpus/fr001_qu-mt.txt`. Not sure where the mistake is. 😅
