### ISSUE TITLE
TypeError: initial_value must be unicode or None, not str

### ISSUE THREAD

**Issue by echan00** [rsennrich/Bleualign#29]
Running into a problem when using Bleualign for the first time:

```
Traceback (most recent call last):
  File "./bleualign/bleualign.py", line 14, in <module>
    a = Aligner(options)
  File "/Users/erikchan/Desktop/play/bleualign/bleualign/align.py", line 162, in __init__
    self._inputObjectFromParameter(self.options['targetfile'])
  File "/Users/erikchan/Desktop/play/bleualign/bleualign/align.py", line 199, in _inputObjectFromParameter
    inputObject = self._stringArray2stringIo(parameter)
  File "/Users/erikchan/Desktop/play/bleualign/bleualign/align.py", line 188, in _stringArray2stringIo
    return io.StringIO('\n'.join([line.rstrip() for line in stringArray]))
TypeError: initial_value must be unicode or None, not str
```

Perhaps this is the issue? https://stackoverflow.com/questions/37948306/type-error-when-sending-command-through-python?rq=1

**Comment by rsennrich** [comment]
thank you for reporting this problem. I can't reproduce it on my machine. Can you please let me know which Python version you're using, and how you're invoking bleualign? Ideally, just use the files `eval/eval1989.de`, `eval/eval1989.fr` and `eval/eval1989.google.fr` so I can reproduce it without needing to exchange files.

**Comment by echan00** [comment]
I am using Python 2.7.10.  I tried invoking 'example/default.py' and still received the same issue. I guess that sort of helps corner the problem to an installation/version issue?

**Comment by echan00** [comment]
FYI I moved default.py to the main directory before executing it so that bleualign.py can be called

**Comment by echan00** [comment]
Weirdly enough, the problem resolved itself. Not entirely sure where or how.
