### ISSUE TITLE
Memory usage increasing

### ISSUE THREAD

**Issue by echan00** [rsennrich/Bleualign#32]
Hi @rsennrich, I've been looping through files and running bleualign on each with a simple script. It is a multiprocessing script but I've come to find that there is a memory issue.

The code below appears to accumulate memory usage the longer it runs and I'm assuming there is a memory leak with bleualign. Would you have an idea whether this is the case and where?

```
files = []	
for file in glob.glob("*.txt"):
	files.append(file)

def bleualign(file):
	print(file)
	cmd = "python3 '../bleualign/bleualign.py' -f sentences --filterthreshold 95 --bleuthreshold 0 -s '../4a_zh-tokenized-converted/"+file+"' -t '../3_en-tokenized/"+file+"' --srctotarget './"+file+"' -o '../5_aligned-zh_95_0/"+file+"'"
	try:
		os.system(cmd)
	except:
		print('error')
	cmd = "python3 '../bleualign/bleualign.py' -f sentences --filterthreshold 95 --bleuthreshold 0.15 -s '../4a_zh-tokenized-converted/"+file+"' -t '../3_en-tokenized/"+file+"' --srctotarget './"+file+"' -o '../5_aligned-zh_95_15/"+file+"'"
	try:
		os.system(cmd)
	except:
		print('error')

def multicore():
	mypool = Pool(processes=number_of_workers, maxtasksperchild=1)
	mypool.map_async(bleualign, files, chunksize=1)
	mypool.close()
	mypool.join()

if __name__=='__main__':
	multicore()

```

Thank you for your help and support with this great library! Btw, I could be very wrong and there is no problem with your library and is my mistake.

EDIT: It appears without the multiprocessing, the memory issues also arise. Doesn't seem like a memory leak, just very heavy memory usage.

**Comment by rsennrich** [comment]
if you have some very large files without article boundaries, this could cause high memory usage - in a first pass, bleualign calculates the BLEU score between every sentence pair. I had a quick look at eval_sents() and the data structure is pruned so it remains at linear complexity at worst, but if you can point me to the part of the code with the heaviest memory usage, I can have another look at it.
