### ISSUE TITLE
TypeError when using Python 2 with empty articles

### ISSUE THREAD

**Issue by alexkillen** [rsennrich/Bleualign#35]
I get the following error when using Python 2( but not with Python3) and have an empty article in my dataset: 

```Traceback (most recent call last):
  File "bleualign.py", line 15, in <module>
    a.mainloop()
  File "/home/alexk/Development/playground/bleualign/bleualign/align.py", line 274, in mainloop
    self.printout(sourcelist, translist, targetlist)
  File "/home/alexk/Development/playground/bleualign/bleualign/align.py", line 977, in printout
    self.out1.write('\n'.join(sources) + '\n')
TypeError: write() argument 1 must be unicode, not str
```
To recreate, either have two .EOA markers one after another, or having a trailing .EOA marker at the end of the file. There may also be other scenarios where this occurs, anything that would result in the `sources` or `targets` list in the printout function being empty when attempting to write them to file.

Obviously the simple workaround is to make sure that those scenarios don't occur, but it raises the question of why it works in Python 3 and not in Python 2.

It appears that the error occurs because when you run:

    '\n'.join(sources) + '\n'

the end result is of type str, rather than unicode, if `sources` is empty. This is due to the fact that when the `sources` list is empty (ordinarily it would be a list of unicode strings) the type of the result will be that of the '\n' string literals, which are of type str in Python 2.

This doesn't occur in Python 3 however, due to string literals being of type unicode.

One way to fix this would be to ensure string literals are in fact unicode when using both Python 2 and 3, which can be done by using the following:

    from __future__ import unicode_literals

However I'm not sure what other side effects this might have.

**Comment by rsennrich** [comment]
thanks, fixed!
