### ISSUE TITLE
Using the -d and -e options override the --source and --target

### ISSUE THREAD

**Issue by alexkillen** [rsennrich/Bleualign#36]
When using the -d or -e options, if they are placed after the --source and --target in the bleualign.py command, then the options['srcfile'] and options['targetfile'] will always be set to the eval source and target files, no matter what is entered in the --source and --target inputs.

If however the -d or -e option is placed before the --source and --target in the command, the options['srcfile'] and options['targetfile'] will be set to the respective --source and --target inputs.

**Comment by rsennrich** [comment]
thanks; this was fixed.
