### ISSUE TITLE
Only parts of the sentences lines are aligned

### ISSUE THREAD

**Issue by twang18** [rsennrich/Bleualign#37]
Hi Rico,
I am trying to test the sentence alignment on my test datasets with the direction of zhen, zhfr, zhru, zhko.  
All four datasets have the same 20 sentence lines (src lang = zh,  so all src_zh.txts are the same, utf-8 texts);
The target lines were translated from our mature nmt engine, and then with the order scrambled (utf-8 texts); 
The srctotarget translation comes from another mature nmt engine. I compared these with the target lines, and the words and translations are pretty much alike, except for the sentence order (utf-8 texts).

With the command like 
`python bleualign.py -s align_test/zhko/src_zh.txt -t align_test/zhko/tar_ko.txt --srctotarget align_test/zhko/src_translation.txt -o align_test/zhko/align_out.txt
`
I only got 7 , 8, 10, 14 sentences aligned for zhen, zhfr, zhko, zhru datasets, respectively.

Steps I took to figure this out:
1. Set Nto1 = 1 in align.py
2. Add `--printemtpy`, still not all 20 sentences lines are shown.
3. Add another dataset of enfr (thought the issue might be due to unsegmented Chinese), however only 10 lines are shown, and with` --printempty `15 lines are shown.
4. Made the srctotarget texts made from the same nmt engine with target lines (therefore the target text and srctotarget text are exactly the same). 
5. Tried with or without tokenizing the target and srctotarget text files on zhen direction. No difference occurred, I still only 7 lines aligned.

However, these steps didn't make any difference.

Could you please enlighten me what tricks I am missing here? Thanks!

**Comment by rsennrich** [comment]
Bleualign implements a monotonicity assumption. Given a parallel text, it's allowed to have sentences that are being merged, inserted or deleted, but it won't find all alignments if sentences are randomly shuffled.

To recover alignments in a scenario with shuffled target side, you need an approach that ignores sentence order ( search for [bitext mining](https://comparable.limsi.fr/bucc2018/bucc2018-task.html) ) - this might be better in some scenarios, but if you actually have two documents that are originally translations of each other (even though there is noise), the monotonicity constraint can reduce noise.

**Comment by twang18** [comment]
Hi Rico,

Thanks for your explicit insights! It is now clear that it is the monotonicity regularization that is filtering out my sentences, rather than quantitative filtering thresholds and bleu scores, even when the filtering options are not on yet.  

Now if I relax my alignment requirement a little and allow partial alignments, are there any possible tricks I can try to recover the number of alignments as much as possible with Bleualign? Will setting bleu n =1 help?

Regarding bitext mining, I did noticed [Bitextor](https://bitextor.readthedocs.io/en/latest/) which integrates your Bleualign as one of the alternative segment alignments option in their pipeline. Hunalign was their default option. Do you think Hunalign might be more applicable to my case?

**Comment by rsennrich** [comment]
Hunalign also assumes monotonicity.

For bitext mining on randomly shuffled data, you'll want to have a similarity score between all possible sentence pairs (regardless of order), then pick the most similar ones. The currently best approach for this is using multilingual sentence embeddings (see [LASER](https://github.com/facebookresearch/LASER/tree/master/tasks/bucc)).

**Comment by twang18** [comment]
This is a very brilliant idea to have the bilingual sentence embedding and apply ANN (Approximate Nearest Neighbor) techniques to find the paired sentences. Thanks for the bringing it, Rico! I will look into it.
