### ISSUE TITLE
Question: Sentence alignment between three languages

### ISSUE THREAD

**Issue by jinamshah** [rsennrich/Bleualign#40]
@rsennrich 
I want to know how do I perform sentence-alignment between three languauges:
eg: dutch - french - english
If I run two commands aligning (dutch and french) and (french and english) then dutch and english are not aligned. 
basically, if I select two pairs out of these three languages, two languages will not be aligned with each other. 
Please help!

**Comment by rsennrich** [comment]
Bleualign is currently hard-coded to only handle two languages, and doing three at once would also increase the search space from quadratic to cubic.

I recommend that you align more than two languages incrementally like this:

let's assume you start with `dutch.nl`, `french.fr`, and `english.en`:

- translate the Dutch text `dutch.nl` to French. Let's call the resulting file `dutch.fr`.
- align the Dutch and French text using the translation. Something like this should work and generate `dutch_french-s` (the Dutch side) and `dutch_french-t` (the French side):

```
bleualign.py --source dutch.nl --target french.fr --srctotarget dutch.fr --output dutch_french
```

- translate the French, aligned text (`dutch_french-t`) to English. Let's call the resulting file `dutch_french.en`.
- paste the aligned French and Dutch files together:

```
paste dutch_french-s dutch_french-t -d "\t" > dutch_french.nlfr
```

- now align the resulting file with the English text, using the English translation of the French text:

```
bleualign.py --source dutch_french.nlfr --target english.en --srctotarget dutch_french.en --output dutch_french_english
```

- split the source side of the resulting file up again, and you'll have all three:

```
cut -f 1 -d "\t" < dutch_french_english-s > dutch_french_english.nl
cut -f 2 -d "\t" < dutch_french_english-s > dutch_french_english.fr
mv dutch_french_english-s  dutch_french_english.en
```

Of course, you swap the order and/or translation directions if that's more convenient.

**Comment by jinamshah** [comment]
Hey @rsennrich thanks for this.
I tried it, and it took a huge toll on the accuracy numbers as compared to aligning two pairs automatically and performing and adjusting the number of lines accordingly for both the pairs.
Can you please suggest some other approach?
 Is changing this possible? 

> Bleualign is currently hard-coded to only handle two languages, and doing three at once would also increase the search space from quadratic to cubic.

> 

>

**Comment by jinamshah** [comment]
After making some changes, it works! 
Thanks!

**Comment by quinnanya** [comment]
@jinamshah What did you do to make it work? I've also got the same problem, where I need to align multiple different languages.

**Comment by jinamshah** [comment]
@quinnanya I'm sorry but I don't remember anything about this tool right now :(
Feel free to reach out to me at hi [at] jinamshah [dot] com to talk specifics
