### ISSUE TITLE
Suggestion settings for book alignment?

### ISSUE THREAD

**Issue by leminhyen2** [rsennrich/Bleualign#43]
Hi, I plan to use bleualign to align sentences between English and Japanese bible which have linear contextual data, not scrambled. Do you have any recommended setting for this task? Also, any suggestion for newer methods or libraries to align linear/organized sentences are welcome

**Comment by rsennrich** [comment]
The default settings should work fine for this purpose. My main recommendation (both for speed and quality) would be to clearly separate parts of the Bible where you have a reliable alignment points (not sure if this would be on the level of books, chapters or verses in your case). Either treat each of these section as a separate file (Bleualign has a batch processing mode for this), or separate them with a line that is ".EOA" (check the eval directory if you're unsure how the files should look).

**Comment by leminhyen2** [comment]
Ah, thank you for the answer. I have one more question if you don't mind,

Does context continuity matter for this repo as long as first line and last line matched? I'm just curious if your library is more similar to [LASER ](https://github.com/facebookresearch/LASER) from Facebook which can mine scrambled text or more like [Vecalign](https://github.com/thompsonb/vecalign) which the author stated that lines should follow context order

**Comment by rsennrich** [comment]
Bleualign and Vecalign are similar in that they find a path of alignments through the document that preserves order.

**Comment by leminhyen2** [comment]
I see. Also thank you the initial research about neural backtranslation. I read your paper and found it very interesting. I wouldn't think that even putting "null" on source side can yield positive result
