### ISSUE TITLE
Where can I get the code for iterative based approach?

### ISSUE THREAD

**Issue by rafu01** [rsennrich/Bleualign#45]
I am looking for the iterative-based approach, as I am working with a dataset of a book translated in two different languages that need to be sentence aligned but I don't have the translation of the source text, I read that the iterative-based approach solves this problem. I am looking for that code. It would be very helpful to me.

**Comment by rsennrich** [comment]
There is no end-to-end code for the iterative approach. Instead, you have to do these steps one-by-one:

- do a first alignment of your parallel corpus based on sentence length (you can use Bleualign with the `--galechurch` argument):
`./bleualign.py --galechurch -s sourcetext.txt -t targettext.txt -o outputfile`
- train your own MT system on `outputfile-s` and `outputfile-t` (using any toolkit of your choice), and translate your training corpus (let's assume the resulting file is called `source.translated.txt`)
- use Bleualign with the original parallel corpus and the translation you created:
`./bleualign.py -s sourcetext.txt -t targettext.txt --srctotarget source.translated.txt -o outputfile2`

**Comment by rafu01** [comment]
thank you!
